### PR TITLE
Allow restore whenever the user feels like it

### LINKED ISSUE #671: Allow restore after device set-up
* [x] potentially pre-uncheck system apps and settings
* [x] run in a foreground service in case user navigates away #203
* [x] in first fresh app start, ask if user wants to restore old backup or start fresh #571
* [x] installing of apps should only happen if not already installed (or on older version)
* [x] handle auto-restore setting (maybe temp disable?)
* [x] enable restore menu item out of dev builds
* [x] remove dialer code (from code and FAQ)
* [x] don't create duplicate files for storage/files restore

### PR DESCRIPTION
**Pull request by grote**
Fixes #671

### CODE REVIEW

**Review by t-m-w — COMMENTED** [review]
This has the problem (mentioned somewhere before) that if you scroll down in the list, the "Restore backup" button disappears. You need to scroll up a little bit for it to reappear.

<details><summary>Video demonstrating the problem</summary>

[screen-20240905-141202.webm](https://github.com/user-attachments/assets/b753c36c-790c-4b0c-bd2b-61f8f9389b64)
</details>

**Comment by grote** [comment]
> This has the problem (mentioned somewhere before) that if you scroll down in the list

yeah, it is not really related to this PR though.

If we wouldn't hide the button when scrolling, it would overlay some ui elements that you couldn't really access then. If we'd put it permanently at the end, we'd lose precious vertical space.

**Comment by t-m-w** [comment]
> > This has the problem (mentioned somewhere before) that if you scroll down in the list
> 
> yeah, it is not really related to this PR though.

Fair, I confirm it inside the wizard, too. I'll open a separate issue for it if there isn't already one.

**Review by t-m-w — DISMISSED** [review]
Seems to work fine! Opened [issue 738](https://github.com/seedvault-app/seedvault/issues/738) for the unrelated problem.

**Review by t-m-w — DISMISSED** [review]

**Review by t-m-w — DISMISSED** [review]

**Review by t-m-w — CHANGES_REQUESTED** [review]
Bleep

**Review by t-m-w — APPROVED** [review]
Bloop

**Review by t-m-w — APPROVED** [review]
I approve

**Comment by VictorVow** [comment]
Is this activated via the [dialler code](https://github.com/seedvault-app/seedvault/wiki/FAQ#how-to-restore-after-passing-through-setup-wizard)?

**Comment by grote** [comment]
No, you use this via normal UI. Main screen 3-dot menu at the top right, then restore.

**Pull request merged**
