### PR TITLE
Don't re-install apps that are already installed and disable auto-restore

### PR DESCRIPTION
**Pull request by grote**
This doesn't re-install apps that are already installed at the same or a newer version. Also, if auto-restore is enabled during install, it disables it and re-enables it when install is complete.

Part of #671

### CODE REVIEW

**Review by t-m-w — COMMENTED** [review]
This works! I have a couple of thoughts, but I'm not sure if they even ought to be addressed:
1. Apps that were already installed do not show app icons, just the generic icon. This looks a little odd alongside apps that were not already installed, as if maybe something went wrong.
2. Apps that were already installed appear so abruptly - especially if all the apps were already installed - that, as above, it looks like maybe something went wrong.

The apps do have green checkmarks, which indicate everything should be fine, but I could see how a user might get a mixed message from the observed behavior.

*Ideally*, it could be communicated somehow that the app was already installed, but I don't think it's necessarily a blocker.

**Review by t-m-w — DISMISSED** [review]

**Comment by grote** [comment]
I think at least the first point should get addressed. However, I can't reproduce it. See this video for how things look for me:

https://github.com/user-attachments/assets/262de625-7544-4fd7-a853-cd150f53b9e7

There's a bit of abruptness when all the apps suddenly show up, but doesn't look bad to me.

**Comment by grote** [comment]
I added two commits related to disabling auto-restore during install to avoid restoring the same data twice for affected apps.

**Comment by t-m-w** [comment]
> I think at least the first point should get addressed. However, I can't reproduce it.

We spoke about this, and there were a few things that came to mind:
1. My backup doesn't have APKs, so it couldn't pull icons or names from those.
2. My backup likely doesn't have icons either, although I'm not really sure how to confirm that. The initial restore selection screen doesn't show either icons or names - is that confirmation enough, maybe?

<details><summary>Screenshot of initial restore selection screen</summary>

Shows a lack of icons and names (just shows package name) for 4 apps.


</details>

So assuming point 2 above is correct, then this is an edge case not worth worrying much about.

**Review by t-m-w — APPROVED** [review]
From a user-facing perspective (no code review or adb, just what I can see happening), this all appears to work fine to me!

**Comment by t-m-w** [comment]
>     2. My backup likely doesn't have icons either

I think this was all true. My backup was from a production build of CalyxOS, for which no stable version currently includes the change to include icons in the backups (should be in 5.10.x which is almost stable). So, it did not have icons or names stored.

I made another backup with the latest upstream code along with these changes, and the described/shown issue is not present. Icons and names are shown.

**Review by stevesoltys — APPROVED** [review]

**Pull request merged**
