### PR TITLE
[From 12 #403] Translations update from Hosted Weblate 

### PR DESCRIPTION
**Pull request by chirayudesai**
Copied from the PR accidentally merged to 12 (and since then, squash reverted)

https://github.com/seedvault-app/seedvault/pull/403

### CODE REVIEW

**Comment by chirayudesai** [comment]
Step 1:

This should be identical to #403 , except that it goes to android13 this time correctly.

Verification: https://github.com/seedvault-app/seedvault/compare/android12 (only diff is this commits, and the revert)

The reverse (https://github.com/seedvault-app/seedvault/compare/android12...android13) also confirms no translation changes

**Comment by chirayudesai** [comment]
Step 2:
https://github.com/seedvault-app/seedvault/pull/468 (identical to https://github.com/seedvault-app/seedvault/pull/469 )

Somehow this conflicts so I thought let's go one step at a time.

**Comment by chirayudesai** [comment]
Step 3: Unlock https://hosted.weblate.org/projects/calyxos/seedvault/#repository (I already changed it to `android13`)

**Comment by chirayudesai** [comment]
> Step 3: Unlock https://hosted.weblate.org/projects/calyxos/seedvault/#repository (I already changed it to `android13`)

Also
* https://hosted.weblate.org/projects/calyxos/seedvault_contactsbackup/#repository
* https://hosted.weblate.org/projects/calyxos/seedvault_storage/#repository

Forgot to lock those earlier. They share VCS

**Review by mikeNG — APPROVED** [review]

**Pull request merged**
