### PR TITLE
Allowlist ProtonDrive

### LINKED ISSUE #432: Add support for Proton Drive
Please add support for Proton Drive (currently in Beta for Android)

### PR DESCRIPTION
**Pull request by chirayudesai**
Fixes: #432

### CODE REVIEW

**Comment by chirayudesai** [comment]
Untested, but I wanted CI to a build an apk for quick testing

**Comment by Forage** [comment]
Thanks @chirayudesai. You missed https://github.com/seedvault-app/seedvault/blob/android14/app/src/debug/res/values/config.xml though.

**Comment by grote** [comment]
If the protonDrive app doesn't support open document tree, we can close this.

**Comment by chirayudesai** [comment]
Unfortunately it looks like we won't be able to add it because the ProtonDrive app does not support `ACTION_OPEN_DOCUMENT_TREE` - which is what we need to store all the backup files.

**Pull request closed without merging**
