### PR TITLE
Use macOS 12 for test workflows, 11 will soon be deprecated

### PR DESCRIPTION
**Pull request by chirayudesai**
More info: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

### CODE REVIEW

**Comment by grote** [comment]
Thanks! Fixes for the failing tests should be in https://github.com/seedvault-app/seedvault/pull/670

**Comment by chirayudesai** [comment]
> Fixes for the failing tests should be in https://github.com/seedvault-app/seedvault/pull/670

If they don't depend on the other changes in that PR, we could move them here.

**Comment by grote** [comment]
got merged, if you rebase, we can see what CI does now.

**Comment by grote** [comment]
maybe we should just disable the instrumentation tests for now?

**Review by grote — APPROVED** [review]

**Pull request merged**
