### PR TITLE
Support edge to edge

### PR DESCRIPTION
**Pull request by theimpulson**

### CODE REVIEW

**Comment by grote** [comment]
Thanks, looks good. Didn't test yet.  But why not also apply this to the other activities?

**Comment by grote** [comment]
I am also curious, why you didn't use `enableEdgeToEdge()` https://developer.android.com/develop/ui/views/layout/edge-to-edge#enable-edge-to-edge-display

**Comment by theimpulson** [comment]
> I am also curious, why you didn't use `enableEdgeToEdge()` https://developer.android.com/develop/ui/views/layout/edge-to-edge#enable-edge-to-edge-display

This is called by default now if an app is targeting Android 15, so we don't need to call it manually

**Comment by theimpulson** [comment]
> Thanks, looks good. Didn't test yet. But why not also apply this to the other activities?

All activities seem to extend `BackupActivity` directly or indirectly except the one I have applied manually.

**Comment by grote** [comment]
Alright, and did you visit all those activities and checked that they look alright? I don't have an Android 15 test device, yet, so I can't check myself.

**Comment by theimpulson** [comment]
> Alright, and did you visit all those activities and checked that they look alright? I don't have an Android 15 test device, yet, so I can't check myself.

Seems fine to me

**Comment by grote** [comment]
Alright, I'll ping you with specific issues if I notice them on 15.

**Review by grote — APPROVED** [review]

**Comment by grote** [comment]
Had a chance to test this on 15. See where the screen at the top cuts things off:

Screenshot_20240923_115629

We are losing lots of vertical space her.e

**Pull request merged**
