### PR TITLE
Merge master into android11 (11-2.2)

### PR DESCRIPTION
**Pull request by chirayudesai**

### CODE REVIEW

**Comment by chirayudesai** [comment]
Once this is merged, I will tag it as 11-2.2, and mark that as the latest release.

Then master will be deprecated, and I will push android11 as android12, per https://github.com/seedvault-app/seedvault/issues/301

**Review by grote — APPROVED** [review]
I didn't read through the entire diff, but the included commits look reasonable.

**Comment by chirayudesai** [comment]
> I didn't read through the entire diff, but the included commits look reasonable.

Only difference to master is translations

```
$ git diff --stat upstream/master
 app/src/main/res/values-ar/strings.xml     |   7 ++
 app/src/main/res/values-bn/strings.xml     |   6 +-
 app/src/main/res/values-cs/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-de/strings.xml     | 104 +++++++++++++-------
 app/src/main/res/values-el/strings.xml     |  42 +++++++-
 app/src/main/res/values-es-rUS/strings.xml |   2 +-
 app/src/main/res/values-es/strings.xml     |  94 ++++++++++++------
 app/src/main/res/values-fi/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-fr/strings.xml     |  57 ++++++++---
 app/src/main/res/values-he/strings.xml     |   2 +-
 app/src/main/res/values-hr/strings.xml     |   2 +-
 app/src/main/res/values-hu/strings.xml     |  68 ++++++++++++-
 app/src/main/res/values-id/strings.xml     |  68 ++++++++++++-
 app/src/main/res/values-is/strings.xml     |   2 +-
 app/src/main/res/values-it/strings.xml     |  69 +++++++++++++-
 app/src/main/res/values-ja/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-ko/strings.xml     |  48 +++++++++-
 app/src/main/res/values-lt/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-ml/strings.xml     |  18 +++-
 app/src/main/res/values-my/strings.xml     |  72 +++++++++++++-
 app/src/main/res/values-nb-rNO/strings.xml |   5 +-
 app/src/main/res/values-night/bools.xml    |   2 +-
 app/src/main/res/values-pl/strings.xml     | 122 +++++++++++++++++++++++-
 app/src/main/res/values-pt-rBR/strings.xml |  48 ++++++++--
 app/src/main/res/values-pt-rPT/strings.xml | 128 ++++++++++++++++++++++++-
 app/src/main/res/values-pt/strings.xml     |  61 +++++++++---
 app/src/main/res/values-ru/strings.xml     |  54 +++++++++--
 app/src/main/res/values-sk/strings.xml     | 147 +++++++++++++++++++++++++++-
 app/src/main/res/values-ta/strings.xml     | 147 +++++++++++++++++++++++++++-
 app/src/main/res/values-te/strings.xml     | 142 ++++++++++++++++++++++++++-
 app/src/main/res/values-tr/strings.xml     |  52 ++++++++--
 app/src/main/res/values-uk/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-vi/strings.xml     | 148 ++++++++++++++++++++++++++++-
 app/src/main/res/values-zh-rCN/strings.xml | 124 +++++++++++++++---------
 34 files changed, 2388 insertions(+), 193 deletions(-)
 ```

**Comment by mikeNG** [comment]
This breaks translations, since they were modified in master for the BIP39 library change.

**Pull request merged**
